services:
    postgres:
      image: postgres:15
      container_name: postgres-db
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: ProductCatalogDb
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
    
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - postgres

    productCatalogService:
      image: productcatalogservice:dev
      container_name: productCatalog
      restart: always
      environment:
        ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ProductCatalogDb;Username=admin;Password=password"
      ports: 
        - "8080:5000"
      depends_on:
        - postgres


volumes:
  postgres_data:
    driver: local
